#db configuration
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    # for local tetsing
    url: jdbc:mysql://localhost:3306/sample_db
    # to test on docker
    #url: jdbc:mysql://host.docker.internal:3306/sample_db # once it deployed on docker
    username: root
    password: fubeus@123
    driver-class-name: com.mysql.cj.jdbc.Driver

# this configuration is for other microservices rather then config microservice
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #for localhost
      defaultZone: http://localhost:8761/eureka/
      #for docker
      #defaultZone: http://registry-container:8761/eureka/